### ISSUE TITLE
Error undefined method `table' for "index_name":String on v1.4.0

### ISSUE THREAD

**Issue by hassan-ahmed** [doctolib/safe-pg-migrations#71]
Hi, thanks for creating an amazing gem.

I ran into an issue on the recent 1.4.0 update, getting an error `undefined method 'table' for "index_name":String` when running a create table migration with `reference` or `belongs_to`
I tested It on 1.3.0 and it works fine

My env:
ruby 2.7.4
rails 5.2.5

Sample migration
```
class CreateComments < ActiveRecord::Migration[5.2]
  def change
    create_table :comments do |t|
      t.references :user, foreign_key: true
      t.string :text, null: false

      t.timestamps
    end
  end
end
```

Logs:
```
Caused by:
NoMethodError: undefined method `table' for "index_comments_on_user_id":String
Did you mean?  tableize
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/idempotent_statements.rb:10:in `add_index'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:76:in `block in add_index'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:121:in `block (2 levels) in without_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:117:in `block in without_lock_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:100:in `with_setting'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:117:in `without_lock_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:121:in `block in without_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:113:in `block in without_statement_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:100:in `with_setting'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:113:in `without_statement_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:121:in `without_timeout'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:76:in `add_index'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/useless_statements_logger.rb:15:in `add_index'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `block in create_table'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in `each'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in `create_table'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/blocking_activity_logger.rb:22:in `block (3 levels) in <module:BlockingActivityLogger>'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/blocking_activity_logger.rb:65:in `log_blocking_queries'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/blocking_activity_logger.rb:22:in `block (2 levels) in <module:BlockingActivityLogger>'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/idempotent_statements.rb:58:in `create_table'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:57:in `block in create_table'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:100:in `with_setting'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:56:in `create_table'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:840:in `say_with_time'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:860:in `method_missing'
/Users/hassan/moodpath-rails/db/migrate/20220227212107_create_comments.rb:3:in `change'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:814:in `exec_migration'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/base.rb:81:in `block in exec_migration'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/base.rb:34:in `block in setup_and_teardown'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/plugins/statement_insurer.rb:100:in `with_setting'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/base.rb:34:in `setup_and_teardown'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/safe-pg-migrations-1.4.0/lib/safe-pg-migrations/base.rb:80:in `exec_migration'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:797:in `block in migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:796:in `migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:977:in `migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1345:in `ddl_transaction'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1262:in `each'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1210:in `migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1036:in `up'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/migration.rb:1011:in `migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `block in load'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/hassan/.rvm/gems/ruby-2.7.4@moodpath-rails/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'

```

**Comment by ThHareau** [comment]
Hi Hassan, thanks for reporting the issue, I'll have a look :)

**Comment by ThHareau** [comment]
Hi @hassan-ahmed, I just pushed a new version of the gem, could you please update your gem to version `1.4.1` and tell me if it works?

**Comment by hassan-ahmed** [comment]
The `1.4.1` update fixed the issue and the migrations work now.
Many thanks for the quick fix 👏

**Comment by ThHareau** [comment]
Great, thanks for reporting the issue Hassan :)
